# Generated by Django 2.0.5 on 2018-07-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PincodeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officename', models.CharField(max_length=1024)),
                ('pincode', models.CharField(max_length=6)),
                ('officetype', models.CharField(choices=[('S.O', 'S.O'), ('B.O', 'B.O'), ('H.O', 'H.O')], max_length=3)),
                ('deliverystatus', models.CharField(choices=[('Delivery', 'DEL'), ('Non-Delivery', 'NOD')], max_length=12)),
                ('divisionname', models.CharField(max_length=1024)),
                ('regionname', models.CharField(max_length=1024)),
                ('circlename', models.CharField(max_length=1024)),
                ('taluk', models.CharField(max_length=1024)),
                ('districtname', models.CharField(max_length=1024)),
                ('statename', models.CharField(max_length=1024)),
            ],
        ),
    ]
